# --- Required options --- #

theme: jekyll-theme-cayman

# Name of website
name: NumPy Geometry
description: Working with geometry using numpy.

# Your name to show in the footer
author: Dan Patterson
  
url: "https://dan-patterson.github.io/numpy_geometry"

# url: https://github.com/Dan-Patterson "https://dan-patterson.github.io/numpy_geometry"
# exclude:
# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
# avatar: "/assets/img/avatar-icon.png"

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
#title-img: /path/to/image

# kramdown
markdown: GFM

# Gems
gems:
  - jekyll-paginate
# --- reference ---
# https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml
