# --- Required options --- #

theme: jekyll-theme-cayman

# Name of website
name: NumPy Geometry
description: Working with geometry using numpy.

# Your name to show in the footer
author: Dan Patterson
  
url: "https://dan-patterson.github.io/numpy_geometry"

# url: https://github.com/Dan-Patterson "https://dan-patterson.github.io/numpy_geometry"
# exclude:
# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
# avatar: "/assets/img/avatar-icon.png"

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
#title-img: /path/to/image

# kramdown
markdown: GFM

navbar-links:
  About Me: "Test about me link"
  Resources:
    - NumPy help: "https://numpy.org/devdocs/user/index.html"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Github home: "https://github.com/Dan-Patterson"
  
toc:
  - title: Documentation
    subfolderitems:
      - page: Backgrounder
        url: Docs/Backgrounder.md
#      - page: Thing 2
#        url: /thing2.html
#      - page: Thing 3
#        url: /thing3.html
#  - title: Group 2
#    subfolderitems:
#      - page: Piece 1
#        url: /piece1.html
#      - page: Piece 2
#        url: /piece2.html
#      - page: Piece 3
#        url: /piece3.html
#  - title: Group 3
#    subfolderitems:
#      - page: Widget 1
#        url: /widget1.html
#      - page: Widget 2
#        url: /widget2.html
#      - page: Widget 3

# Alternatively, the navbar, footer, and page background can be set to an image
# instead of colour

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Gems
#gems:
#  - jekyll-paginate
# --- reference ---
# https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml
